In [1]:
import numpy as np
import nltk
from sklearn.metrics import cohen_kappa_score as k

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('/home/ramendra/virtualenv_name/data/training_set_rel3.xls')
data

essay_id  essay_set                                              essay  \
0             1          1  Dear local newspaper, I think effects computer...   
1             2          1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2             3          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3             4          1  Dear Local Newspaper, @CAPS1 I have found that...   
4             5          1  Dear @LOCATION1, I know having computers has a...   
5             6          1  Dear @LOCATION1, I think that computers have a...   
6             7          1  Did you know that more and more people these d...   
7             8          1  @PERCENT1 of people agree that computers make ...   
8             9          1  Dear reader, @ORGANIZATION1 has had a dramatic...   
9            10          1  In the @LOCATION1 we have the technology of a ...   
10           11          1  Dear @LOCATION1, @CAPS1 people acknowledge the...   
11           12          1  Dear @CAPS1 @CAPS2 I feel that computers do ta...   
12           13          1  Dear local newspaper I raed ur argument on the...   
13           14          1  My three detaileds for this news paper article...   
14           15          1  Dear, In this world today we should have every...   
15           16          1  Dear @ORGANIZATION1, The computer blinked to l...   
16           17          1  Dear Local Newspaper, I belive that computers ...   
17           18          1  Dear Local Newspaper, I must admit that the ex...   
18           19          1  I aegre waf the evansmant ov tnachnolage. The ...   
19           20          1  Well computers can be a good or a bad thing. I...   
20           21          1  Dear @CAPS1 of the @CAPS2 @CAPS3 daily, I am w...   
21           22          1  Dear local Newspaper @CAPS1 a take all your co...   
22           23          1  Dear local newspaper, @CAPS1 you ever see a ch...   
23           24          1  Dear local newspaper, I've heard that not many...   
24           25          1  Dear @CAPS1, @CAPS2 off, I beileve that comput...   
25           26          1  Do you think that computers are useless? Or do...   
26           27          1  Computers a good because you can get infermati...   
27           28          1  Dear Newspaper, Computers are high tec and hav...   
28           29          1  Dear local newspaper, @CAPS1 people throughout...   
29           30          1  Dear Newspaper People, I think that computers ...   
...         ...        ...                                                ...   
12948     21592          8   We all understand the benefits of laughter. L...   
12949     21594          8        It was midsummer, and i could feel the c...   
12950     21595          8   Have you ever experienced a time with your fr...   
12951     21596          8   I woke up just like any other day happy yet l...   
12952     21598          8   Laughter is an important part of my life, eit...   
12953     21599          8   I sat at the table, speechless, as they told ...   
12954     21601          8   As I remember back, it was @DATE1. It was a h...   
12955     21603          8   Those eyes, it was like I was looking out int...   
12956     21604          8  Some say that laugh is the common language bet...   
12957     21605          8   Laughter is an integral element to many situa...   
12958     21606          8  One time I was at my friend @PERSON1's house, ...   
12959     21607          8   LAUGHTER @CAPS1 knows that laughter is a heal...   
12960     21608          8  One thing that people in the world love to do ...   
12961     21609          8   Laughter, to me, is an important aspect of my...   
12962     21610          8   People always say that the worst parts of lif...   
12963     21611          8   Why is it that people can look back at someth...   
12964     21613          8   Before my best friend moved away, we would st...   
12965     21615          8            

In [4]:
a=[ix for ix in range(10,28)]
a = np.array(a)
a = np.append(a,np.array([0,3,4,5,7,8]))
# # a.append([0,3,4,5,7,8])
data.drop(data.columns[a],axis=1,inplace=True)
data

essay_set                                              essay  \
0              1  Dear local newspaper, I think effects computer...   
1              1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2              1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3              1  Dear Local Newspaper, @CAPS1 I have found that...   
4              1  Dear @LOCATION1, I know having computers has a...   
5              1  Dear @LOCATION1, I think that computers have a...   
6              1  Did you know that more and more people these d...   
7              1  @PERCENT1 of people agree that computers make ...   
8              1  Dear reader, @ORGANIZATION1 has had a dramatic...   
9              1  In the @LOCATION1 we have the technology of a ...   
10             1  Dear @LOCATION1, @CAPS1 people acknowledge the...   
11             1  Dear @CAPS1 @CAPS2 I feel that computers do ta...   
12             1  Dear local newspaper I raed ur argument on the...   
13             1  My three detaileds for this news paper article...   
14             1  Dear, In this world today we should have every...   
15             1  Dear @ORGANIZATION1, The computer blinked to l...   
16             1  Dear Local Newspaper, I belive that computers ...   
17             1  Dear Local Newspaper, I must admit that the ex...   
18             1  I aegre waf the evansmant ov tnachnolage. The ...   
19             1  Well computers can be a good or a bad thing. I...   
20             1  Dear @CAPS1 of the @CAPS2 @CAPS3 daily, I am w...   
21             1  Dear local Newspaper @CAPS1 a take all your co...   
22             1  Dear local newspaper, @CAPS1 you ever see a ch...   
23             1  Dear local newspaper, I've heard that not many...   
24             1  Dear @CAPS1, @CAPS2 off, I beileve that comput...   
25             1  Do you think that computers are useless? Or do...   
26             1  Computers a good because you can get infermati...   
27             1  Dear Newspaper, Computers are high tec and hav...   
28             1  Dear local newspaper, @CAPS1 people throughout...   
29             1  Dear Newspaper People, I think that computers ...   
...          ...                                                ...   
12948          8   We all understand the benefits of laughter. L...   
12949          8        It was midsummer, and i could feel the c...   
12950          8   Have you ever experienced a time with your fr...   
12951          8   I woke up just like any other day happy yet l...   
12952          8   Laughter is an important part of my life, eit...   
12953          8   I sat at the table, speechless, as they told ...   
12954          8   As I remember back, it was @DATE1. It was a h...   
12955          8   Those eyes, it was like I was looking out int...   
12956          8  Some say that laugh is the common language bet...   
12957          8   Laughter is an integral element to many situa...   
12958          8  One time I was at my friend @PERSON1's house, ...   
12959          8   LAUGHTER @CAPS1 knows that laughter is a heal...   
12960          8  One thing that people in the world love to do ...   
12961          8   Laughter, to me, is an important aspect of my...   
12962          8   People always say that the worst parts of lif...   
12963          8   Why is it that people can look back at someth...   
12964          8   Before my best friend moved away, we would st...   
12965          8                                @ORGANIZATION1  ...   
12966          8   Morose and somnolent, I woke up. I woke up to...   
12967          8   A while back my mom had decided to send me to...   
12968          8                              I dont like computers   
12969          8   Everyone knows how important a laugh can be. ...   
12970          8   Laughter is an important part of my family. W...   
12971          8   laughter is an important part of any kind of ...   
12972          8  Sometime ago 

In [5]:
data1 = data.loc[data['essay_set']==1]
data2 = data.loc[data['essay_set']==2]
data3 = data.loc[data['essay_set']==3]
data4 = data.loc[data['essay_set']==4]
data5 = data.loc[data['essay_set']==5]
data6 = data.loc[data['essay_set']==6]
data7 = data.loc[data['essay_set']==7]
data8 = data.loc[data['essay_set']==8]

In [6]:
data1.drop(data1.columns[[3]],axis=1,inplace=True)
data3.drop(data3.columns[[3]],axis=1,inplace=True)
data4.drop(data4.columns[[3]],axis=1,inplace=True)
data5.drop(data5.columns[[3]],axis=1,inplace=True)
data6.drop(data6.columns[[3]],axis=1,inplace=True)
data7.drop(data7.columns[[3]],axis=1,inplace=True)
data8.drop(data8.columns[[3]],axis=1,inplace=True)
data8

/home/ramendra/.local/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


essay_set                                              essay  \
12255          8   A long time ago when I was in third grade I h...   
12256          8   Softball has to be one of the single most gre...   
12257          8   Some people like making people laugh, I love ...   
12258          8   "LAUGHTER"  @CAPS1 I hang out with my friends...   
12259          8  Well ima tell a story about the time i got @CA...   
12260          8  @CAPS3 I'm going to tell @CAPS18 a little stor...   
12261          8   My best friend, @PERSON1 and I have been clos...   
12262          8    Laughter is a really good thing to have in a...   
12263          8   I believe that with all people laughter, and ...   
12264          8   Laughter, one of life's greatest gifts. Have ...   
12265          8   Laugher Laughter is to express delight, fun, ...   
12266          8   Starting a story out with two @NUM1 @DATE1 ol...   
12267          8  When i meet new people its like alright cause ...   
12268          8   People always say laughter is a big part in a...   
12269          8      "Laughter is the best medicine." The phras...   
12270          8   one time when i was skateboarding with my fri...   
12271          8                 "Laughter" A good relationship ...   
12272          8   Laughter. A story about laughter is what you ...   
12273          8   Laughter is a big part in my relationship. I ...   
12274          8   Everyone enjoys laughter. Everywhere you look...   
12275          8   Why is it that laughter can bring people so c...   
12276          8   "@CAPS1 figure something out to do! I am real...   
12277          8  Interesting fly.It was the @DATE1 of this @DAT...   
12278          8   In many relationships I have had, there has a...   
12279          8   These days you don't really need a reason to ...   
12280          8  Friends are'nt always what we want them to be ...   
12281          8    It was a normal bright and warm @DATE1 day, ...   
12282          8  Making someone laugh is the best feeling to th...   
12283          8   "Laughter is the key to the soul." @CAPS1 you...   
12284          8   Their are many joys in life, some are more re...   
...          ...                                                ...   
12948          8   We all understand the benefits of laughter. L...   
12949          8        It was midsummer, and i could feel the c...   
12950          8   Have you ever experienced a time with your fr...   
12951          8   I woke up just like any other day happy yet l...   
12952          8   Laughter is an important part of my life, eit...   
12953          8   I sat at the table, speechless, as they told ...   
12954          8   As I remember back, it was @DATE1. It was a h...   
12955          8   Those eyes, it was like I was looking out int...   
12956          8  Some say that laugh is the common language bet...   
12957          8   Laughter is an integral element to many situa...   
12958          8  One time I was at my friend @PERSON1's house, ...   
12959          8   LAUGHTER @CAPS1 knows that laughter is a heal...   
12960          8  One thing that people in the world love to do ...   
12961          8   Laughter, to me, is an important aspect of my...   
12962          8   People always say that the worst parts of lif...   
12963          8   Why is it that people can look back at someth...   
12964          8   Before my best friend moved away, we would st...   
12965          8                                @ORGANIZATION1  ...   
12966          8   Morose and somnolent, I woke up. I woke up to...   
12967          8   A while back my mom had decided to send me to...   
12968          8                              I dont like computers   
12969          8   Everyone knows how important a laugh can be. ...   
12970          8   Laughter is an important part of my family. W...   
12971          8   laughter is an important part of any kind of ...   
12972          8  Sometime ago 

## TRAINING


In [7]:
data8

essay_set                                              essay  \
12255          8   A long time ago when I was in third grade I h...   
12256          8   Softball has to be one of the single most gre...   
12257          8   Some people like making people laugh, I love ...   
12258          8   "LAUGHTER"  @CAPS1 I hang out with my friends...   
12259          8  Well ima tell a story about the time i got @CA...   
12260          8  @CAPS3 I'm going to tell @CAPS18 a little stor...   
12261          8   My best friend, @PERSON1 and I have been clos...   
12262          8    Laughter is a really good thing to have in a...   
12263          8   I believe that with all people laughter, and ...   
12264          8   Laughter, one of life's greatest gifts. Have ...   
12265          8   Laugher Laughter is to express delight, fun, ...   
12266          8   Starting a story out with two @NUM1 @DATE1 ol...   
12267          8  When i meet new people its like alright cause ...   
12268          8   People always say laughter is a big part in a...   
12269          8      "Laughter is the best medicine." The phras...   
12270          8   one time when i was skateboarding with my fri...   
12271          8                 "Laughter" A good relationship ...   
12272          8   Laughter. A story about laughter is what you ...   
12273          8   Laughter is a big part in my relationship. I ...   
12274          8   Everyone enjoys laughter. Everywhere you look...   
12275          8   Why is it that laughter can bring people so c...   
12276          8   "@CAPS1 figure something out to do! I am real...   
12277          8  Interesting fly.It was the @DATE1 of this @DAT...   
12278          8   In many relationships I have had, there has a...   
12279          8   These days you don't really need a reason to ...   
12280          8  Friends are'nt always what we want them to be ...   
12281          8    It was a normal bright and warm @DATE1 day, ...   
12282          8  Making someone laugh is the best feeling to th...   
12283          8   "Laughter is the key to the soul." @CAPS1 you...   
12284          8   Their are many joys in life, some are more re...   
...          ...                                                ...   
12948          8   We all understand the benefits of laughter. L...   
12949          8        It was midsummer, and i could feel the c...   
12950          8   Have you ever experienced a time with your fr...   
12951          8   I woke up just like any other day happy yet l...   
12952          8   Laughter is an important part of my life, eit...   
12953          8   I sat at the table, speechless, as they told ...   
12954          8   As I remember back, it was @DATE1. It was a h...   
12955          8   Those eyes, it was like I was looking out int...   
12956          8  Some say that laugh is the common language bet...   
12957          8   Laughter is an integral element to many situa...   
12958          8  One time I was at my friend @PERSON1's house, ...   
12959          8   LAUGHTER @CAPS1 knows that laughter is a heal...   
12960          8  One thing that people in the world love to do ...   
12961          8   Laughter, to me, is an important aspect of my...   
12962          8   People always say that the worst parts of lif...   
12963          8   Why is it that people can look back at someth...   
12964          8   Before my best friend moved away, we would st...   
12965          8                                @ORGANIZATION1  ...   
12966          8   Morose and somnolent, I woke up. I woke up to...   
12967          8   A while back my mom had decided to send me to...   
12968          8                              I dont like computers   
12969          8   Everyone knows how important a laugh can be. ...   
12970          8   Laughter is an important part of my family. W...   
12971          8   laughter is an important part of any kind of ...   
12972          8  Sometime ago 

In [8]:
from nltk.tokenize import word_tokenize

In [9]:
data8.shape[0]
data8 = data8.reset_index()

In [10]:
data8['essay'][0]

" A long time ago when I was in third grade I had a friend @PERSON2 who's mom was in a bad mood. She never laughed and she never smiled. Every time I saw her I would smile at her and all she would do was frown and keep walking. At first I didn't know she was a grouch i just thought she didn't like me or something.When @PERSON2 told me his mom was a grouch I started to laugh and laugh. He asked me what was so funny i told him that i thought his mom didn't like me or something because every time I see his mom I would smile at her and all she will do is frown and walk away. That made my friend laugh we were cracking up so hard that we got in trouble in class.   The next day @PERSON2 and I were eating lunch at school when he says to me &lt;hey your pretty good at making people laugh&gt;. I said &lt;no I am not my jokesare horrible&gt;. He said &lt;@CAPS1 lets put them to the test go up to some one new to this school&gt;. I said @CAPS1 so we went around the whole school looking for a new st

In [11]:
allsentences = np.array([data8['essay'][ix] for ix in range(data8.shape[0])])
print(allsentences.shape)
allsentences_list = allsentences.tolist()

(723,)


In [12]:
from nltk.tokenize import sent_tokenize, word_tokenize
# words1 = word_tokenize(allsentences[0])
# type(words1)

In [13]:
# words = word_tokenize(allsentences[0])
# print(words)
from nltk.tokenize import RegexpTokenizer
import re
tokenizer1 = re.compile(r'\b[A-Z][A-Z0-9]+\b')
tokenizer2 = RegexpTokenizer('[ \d \' \. \, \: \; \? \- \! \( \) \s\@]')
prop_nouns=[[] for ix in range(data8.shape[0])]
for ix in range(data8.shape[0]):
        prop_nouns[ix] = np.unique(np.append(prop_nouns[ix],np.array(tokenizer2.tokenize(allsentences[ix]))))
        prop_nouns[ix] = np.unique(np.append(prop_nouns[ix],np.array(tokenizer1.findall(allsentences[ix]))))
        prop_nouns[ix] = prop_nouns[ix].tolist()

In [14]:
words = [[] for ix in range(data8.shape[0])]
for ix in range(data8.shape[0]):
    words[ix] = np.array(word_tokenize(allsentences[ix]))

# feature1-word count
feature1 = np.array([])
words_updated = [[] for ix in range(data8.shape[0])]
for ix in range(data8.shape[0]):
    words_updated[ix] = np.array([w for w in words[ix] if w not  in prop_nouns[ix]])
    a = list(words_updated[ix].shape)
    feature1 = np.append(feature1,a[0])

words_updated = np.array(words_updated)
feature1

array([696., 781., 873., 698., 620., 642., 806., 293., 753., 512., 433.,
       774., 818., 558., 724., 131., 709., 532., 735., 273., 616., 824.,
       458., 885., 361., 675., 619., 835., 225., 741., 703., 849., 750.,
       788., 859., 459., 801., 300., 804., 806., 646., 806., 835., 444.,
       354., 470., 463., 533., 314., 656., 465., 576., 659., 750., 560.,
       626., 484., 370., 555., 319., 287., 778., 649., 601., 769., 240.,
       510., 848., 402., 430., 853., 574., 426., 589., 832., 814., 464.,
       812., 767., 258., 829., 336., 808., 769., 791., 534., 510., 644.,
       561., 245., 548., 613., 292., 781., 650., 629., 494., 278., 173.,
       317., 655., 848., 797., 570., 536., 839., 849., 240., 433., 518.,
       530., 362., 543., 843., 504., 496., 758., 491., 833., 784., 763.,
       291.,  64., 572., 503., 703., 608., 708., 623., 703., 731., 471.,
       667., 343., 480., 697., 493., 506., 419., 748., 513., 184., 248.,
       828., 729., 601., 675., 677., 581., 800., 41

In [15]:
# feature2-sentence count
sentence = [[] for ix in range(data8.shape[0])]
feature2 = np.array([])
for ix in range(data8.shape[0]):
    sentence[ix] = np.array(sent_tokenize(allsentences[ix]))
    feature2 = np.append(feature2,sentence[ix].shape[0])

feature2

array([39., 30., 39., 30., 26., 72., 82., 17., 48., 40., 18., 37., 17.,
       31., 54.,  4., 41., 38., 52., 30., 28., 61.,  7., 32., 22., 40.,
       37., 36., 17., 18., 27., 62., 64., 54., 61., 22., 53.,  6., 47.,
       56., 60., 52., 80., 24., 27., 30., 43., 28., 13., 30., 43., 30.,
       32., 40., 43., 39., 31., 29., 34., 22., 29., 56., 36., 37., 70.,
       12., 45., 31., 20., 21., 43., 34., 32., 43., 56., 70., 24., 77.,
       32., 19., 20., 17., 65., 47., 42., 47., 31., 83., 50., 12., 49.,
       37.,  9., 45., 57., 36., 30., 19.,  1., 23., 38., 44., 60., 37.,
       34., 48., 32., 14., 30., 36., 22., 26., 43., 56., 26., 29., 62.,
       32., 53., 59., 70., 18.,  4., 43.,  5., 32., 36., 26., 24., 34.,
       54., 29., 36., 15.,  4., 42., 28., 20., 24., 43., 33., 18., 23.,
       45., 47., 29., 59., 34., 26., 48., 26., 50., 28., 44., 22., 37.,
       22., 45., 70., 33., 41.,  4., 19., 17., 47., 15., 29., 12., 24.,
       48., 35., 27.,  9., 49., 70., 33., 18., 37., 37., 52., 18

In [16]:
# feature3 - average word length
feature3 = np.array([])
for ix in range(data8.shape[0]):
    feature3 = np.append(feature3, np.sum((len(w)/words_updated[ix].shape[0]) for w in words_updated[ix]))

feature3

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([3.43103448, 3.93854033, 3.96907216, 3.66905444, 3.38548387,
       3.64018692, 3.83870968, 3.86006826, 4.15670651, 4.18945312,
       3.93995381, 4.04780362, 3.61246944, 4.11648746, 4.19198895,
       4.51145038, 4.04231312, 3.89849624, 3.71972789, 4.19413919,
       3.87012987, 3.9684466 , 4.10043668, 3.63615819, 4.04155125,
       3.87259259, 3.83521809, 3.91736527, 4.12      , 3.90688259,
       3.87908962, 3.80683157, 3.80133333, 4.02791878, 3.99767171,
       3.96514161, 3.84769039, 3.67      , 4.12810945, 4.1426799 ,
       3.91021672, 4.04590571, 4.07305389, 4.05855856, 4.02542373,
       3.61276596, 3.78185745, 3.5478424 , 3.88853503, 3.77134146,
       3.93333333, 4.00347222, 3.81335357, 3.79333333, 4.06428571,
       3.87859425, 3.95867769, 4.03783784, 4.06126126, 4.27899687,
       3.93379791, 4.09383033, 4.02619414, 3.90848586, 4.        ,
       4.15      , 4.02941176, 3.72287736, 3.97263682, 3.87209302,
       3.95310668, 3.98432056, 3.61032864, 3.87266553, 3.77163

In [17]:
stopwords = np.array([])
for ix in range(data8.shape[0]):
    stopwords = np.append(stopwords, np.array(w for w in prop_nouns[ix]))

stopwords.tolist()
stopwords = set(stopwords)
allsentences.shape

(723,)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words=stopwords,ngram_range=(1,2))
cv.fit_transform(allsentences[:500]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
a1 = cv.transform(allsentences_list).toarray()

In [20]:
#feature 4: weighted word-counts
feature4 = np.array([])
for ix in range(data8.shape[0]):
    feature4 = np.append(feature4, np.sum(a for a in a1[ix]))
    
feature4

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([1283., 1411., 1539., 1333., 1149., 1285., 1549.,  559., 1415.,
       1025.,  839., 1527., 1501., 1061., 1503.,  255., 1337., 1001.,
       1417.,  545., 1201., 1631.,  949., 1543.,  669., 1255., 1143.,
       1587.,  435., 1377., 1437., 1527., 1353., 1601., 1609.,  857.,
       1573.,  543., 1653., 1607., 1207., 1611., 1643.,  825.,  665.,
       1043.,  909., 1043.,  613., 1269.,  919., 1103., 1195., 1427.,
       1093., 1119.,  949.,  685., 1061.,  619.,  535., 1479., 1205.,
       1113., 1607.,  455., 1087., 1573.,  775.,  787., 1585., 1041.,
        861., 1099., 1537., 1591.,  893., 1589., 1441.,  481., 1615.,
        597., 1591., 1415., 1493., 1053.,  979., 1247., 1115.,  463.,
       1097., 1171.,  579., 1485., 1183., 1223., 1011.,  527.,  329.,
        611., 1237., 1547., 1623., 1061.,  987., 1549., 1619.,  431.,
        845.,  993.,  981.,  713., 1089., 1555.,  951.,  959., 1475.,
        993., 1547., 1477., 1489.,  545.,  133., 1141.,  957., 1333.,
       1185., 1267.,

In [21]:
feature4.shape

(723,)

In [22]:
#feature5: Punctuation
feature5 = np.array([])
for ix in range(data8.shape[0]):
    a = np.array(tokenizer2.tokenize(allsentences[ix]))
    feature5 = np.append(feature5, len(a))
    
feature5

array([ 833.,  870.,  957.,  798.,  738., 1202., 1122.,  317.,  872.,
        712.,  507., 1046.,  843.,  637., 1139.,  144.,  868.,  596.,
        844.,  336.,  739., 1077.,  640.,  925.,  392.,  778.,  700.,
        900.,  288.,  812.,  858., 1033.,  926., 1118.,  979.,  523.,
       1055.,  361., 1122., 1069.,  869., 1138., 1120.,  522.,  445.,
        829.,  607.,  626.,  375.,  773.,  684.,  728.,  741.,  909.,
        732.,  682.,  596.,  465.,  682.,  376.,  343.,  911.,  703.,
        706., 1215.,  271.,  851.,  938.,  491.,  493.,  978.,  692.,
        655.,  708.,  995., 1173.,  510., 1029.,  894.,  326.,  962.,
        361., 1050.,  884.,  954.,  666.,  568.,  876.,  848.,  287.,
        805.,  714.,  317.,  929.,  810.,  750.,  665.,  315.,  180.,
        351.,  748., 1123., 1172.,  635.,  641., 1004.,  947.,  276.,
        546.,  619.,  597.,  512.,  874., 1000.,  569.,  638.,  906.,
        714.,  914.,  934.,  960.,  336.,   78.,  790.,  557.,  796.,
        685.,  745.,

In [23]:
feature5.shape

(723,)

In [24]:
# feature 6: Comma Separation
feature6 = np.array([])
for ix in range(data8.shape[0]):
    feature6 = np.append(feature6,np.sum(words[ix]==','))
                         
feature6

array([ 0., 33., 37.,  7.,  3., 35., 38.,  5., 37., 30., 24., 32.,  7.,
       17., 51.,  0., 29.,  9., 24., 12., 33., 16., 15., 18.,  8., 10.,
       21., 16., 20., 39.,  5., 20., 51., 61., 25., 27.,  5.,  8., 54.,
       48., 26., 47., 39., 29., 12., 12.,  6.,  3., 10., 23., 30., 18.,
       19., 25., 37.,  8., 28.,  9., 25., 13., 14., 19.,  6., 17., 28.,
       12., 11.,  1., 14.,  8., 27., 21., 21., 42., 21., 53., 17., 30.,
       15.,  6., 23.,  5., 34., 35., 51., 17.,  8., 49., 34., 13., 42.,
        9.,  0., 29., 37., 31., 19., 10.,  0.,  1., 23., 68., 40., 15.,
       35., 59., 32.,  7., 13., 23.,  8., 27., 26., 39.,  9., 15., 37.,
       22.,  5., 45., 24., 12.,  2., 20.,  9., 15.,  5., 14., 52., 15.,
        9., 14., 24.,  8.,  9., 14., 46., 34., 12., 38.,  9., 11.,  6.,
       22., 27., 22., 15., 54.,  4., 13.,  5., 17., 16., 25., 13., 24.,
       16., 50., 37., 24., 12.,  5.,  6., 23., 45., 24., 25.,  5.,  8.,
       59., 49.,  8.,  2., 45., 51., 48., 16., 15., 33., 13.,  2

In [25]:
feature6.shape

(723,)

In [26]:
# feature 7: Proper Noun
feature7 = np.array([])
for ix in range(data8.shape[0]):
    feature7 = np.append(feature7,np.sum(words[ix]=='@'))
                         
feature7

array([ 36.,   6.,   0.,  15.,  29., 145.,  65.,   0.,   8.,  43.,   9.,
        69.,   2.,  11.,  78.,   0.,  28.,   7.,  10.,   7.,  19.,  62.,
        56.,   6.,   2.,  16.,   4.,   3.,  11.,   3.,  42.,  38.,  25.,
        61.,  14.,   4.,  52.,   7.,  70.,  56.,  43.,  65.,  60.,   5.,
        18.,  98.,  22.,  19.,  14.,  22.,  48.,  32.,   9.,  30.,  20.,
         1.,  19.,  10.,  20.,   7.,   5.,  19.,   1.,  16., 101.,   3.,
        94.,  20.,   9.,   6.,  18.,  23.,  51.,   9.,  30.,  69.,   2.,
        37.,   2.,  13.,  26.,   0.,  48.,  12.,  28.,  23.,   6.,  27.,
        68.,   6.,  48.,  19.,   4.,  27.,  26.,  18.,  34.,   2.,   2.,
         3.,  11.,  49.,  95.,   6.,  11.,  19.,  13.,   6.,  25.,  14.,
        16.,  21.,  84.,  19.,   2.,  26.,  15.,  40.,   7.,  16.,  24.,
         5.,   4.,  49.,  14.,  15.,  13.,   4.,  19., 117.,  40.,  11.,
        17.,   1.,  11.,  19.,  41.,  30.,   9.,  14.,  18.,  16.,   1.,
        53.,  55.,  29.,  62.,   1.,  69.,  30.,   

In [27]:
feature7.shape

(723,)

In [28]:
##GRAMMATICAL EXTRACTION
words_updated = words_updated.tolist()

In [29]:
# nltk.download('averaged_perceptron_tagger')
tagged = [[] for ix in range(data8.shape[0])]
for ix in range(data8.shape[0]):
    tagged[ix] = nltk.pos_tag(word_tokenize(allsentences[ix]))
np.array(tagged[0]).shape

(835, 2)

In [30]:
# feature8 - noun
feature8 = np.array([])
for ix in range(data8.shape[0]):
    feature8 = np.append(feature8,np.sum(x[1]=='NN' or x[1]=='NNS' or x[1] == 'NNP' for x in tagged[ix]))

feature8

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([178., 151., 158., 138., 165., 322., 216.,  56., 151., 160., 117.,
       259., 160., 111., 230.,  28., 145.,  91., 144.,  70., 144., 249.,
       177., 107.,  61., 133.,  91., 136.,  55., 131., 160., 140., 145.,
       236., 160.,  98., 231.,  62., 256., 218., 165., 251., 229.,  79.,
        76., 237., 108., 101.,  74., 121., 163., 168., 124., 174., 149.,
       103., 122.,  73., 116.,  80.,  73., 171., 102., 102., 312.,  45.,
       208., 138.,  84.,  90., 135., 137., 154., 110., 189., 226.,  82.,
       222., 149.,  50., 203.,  59., 268., 141., 200., 156.,  86., 178.,
       206.,  66., 186., 129.,  43., 177., 129., 140., 125.,  62.,  38.,
        69., 132., 220., 260.,  93.,  96., 163., 122.,  62.,  94., 113.,
       105., 110., 227., 155.,  83., 122., 158., 145., 156., 147., 158.,
        49.,  19., 200., 121., 164., 127.,  78., 167., 294., 202.,  96.,
       164.,  60.,  88., 183., 157., 118.,  92., 129., 116.,  50.,  59.,
       228., 173., 134., 228., 125., 247., 149.,  6

In [31]:
feature8.shape

(723,)

In [32]:
# feature9 - verb
feature9 = np.array([])
for ix in range(data8.shape[0]):
    feature9 = np.append(feature9,np.sum(x[1]=='VB' or x[1]=='VBD' or x[1] == 'VBG' for x in tagged[ix]))

feature9

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([147., 130., 127.,  86., 132.,  73., 140.,  21.,  77.,  54.,  59.,
       118., 110.,  77.,  98.,  21., 105.,  67.,  73.,  16.,  94., 149.,
        94., 133.,  53., 113., 117., 130.,  25.,  83., 130., 178., 127.,
       162., 135.,  64., 140.,  49., 146., 145., 127., 140., 111.,  67.,
        74.,  90.,  80., 118.,  57., 110.,  72.,  83.,  76.,  74., 101.,
        72.,  67.,  28.,  98.,  40.,  35., 141.,  82., 131., 153.,  27.,
       106., 118.,  57.,  75., 117.,  99., 102.,  77., 130., 158.,  48.,
       146.,  79.,  44., 107.,  43., 128.,  95., 135.,  60.,  45., 113.,
       117.,  44.,  97.,  94.,  64., 103., 133.,  81.,  58.,  43.,  32.,
        42.,  82., 144., 134.,  92.,  99., 155., 103.,  26.,  73.,  79.,
        84.,  46., 105., 185.,  72.,  72., 137.,  69., 174., 119., 160.,
        45.,   4., 117.,  47., 103.,  89., 130.,  87., 135., 113.,  85.,
        92.,  53., 110.,  97.,  75.,  72.,  61., 137.,  75.,  31.,  26.,
       144., 148.,  99.,  67.,  91., 101., 153.,  4

In [33]:
# feature10 - adjective
feature10 = np.array([])
for ix in range(data8.shape[0]):
    feature10 = np.append(feature10,np.sum(x[1]=='JJ' or x[1]=='JJR' or x[1] == 'JJS' for x in tagged[ix]))

feature10

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([42., 45., 58., 38., 50., 64., 68., 24., 67., 50., 25., 76., 65.,
       49., 83., 11., 73., 42., 52., 28., 36., 62., 52., 58., 22., 48.,
       37., 55., 23., 60., 57., 57., 64., 61., 60., 37., 56., 19., 63.,
       79., 45., 42., 83., 23., 28., 53., 29., 27., 20., 49., 51., 47.,
       62., 59., 43., 48., 47., 40., 59., 22., 17., 50., 50., 44., 95.,
       17., 60., 36., 38., 25., 71., 52., 18., 28., 75., 68., 36., 59.,
       53., 18., 57., 26., 72., 48., 64., 46., 37., 50., 55., 15., 73.,
       34., 11., 53., 37., 41., 52., 12.,  6., 12., 42., 77., 76., 57.,
       46., 64., 82., 21., 31., 44., 39., 34., 52., 36., 45., 44., 53.,
       40., 30., 41., 39., 28.,  6., 34., 63., 67., 45., 56., 44., 57.,
       65., 32., 58., 18., 30., 52., 43., 50., 22., 45., 42., 21., 14.,
       92., 62., 40., 41., 48., 53., 67., 33., 40., 21., 61., 21., 51.,
       41., 57., 99., 59., 43., 28., 13., 45., 60., 20., 56., 20., 20.,
       53., 68., 26., 13., 85., 82., 43., 25., 49., 67., 42., 16

In [34]:
# feature 11 - adverb
feature11 = np.array([])
for ix in range(data8.shape[0]):
    feature11 = np.append(feature11,np.sum(x[1]=='RB' or x[1]=='RBR' or x[1] == 'RBS' for x in tagged[ix]))

feature11

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([ 29.,  74.,  62.,  54.,  64.,  42.,  61.,  29.,  56.,  57.,  20.,
        64.,  73.,  42.,  57.,   6.,  51.,  54.,  55.,  16.,  48.,  56.,
        40.,  87.,  29.,  46.,  46.,  49.,  16.,  59.,  45.,  73.,  65.,
        42.,  56.,  41.,  58.,  27.,  45.,  73.,  54.,  78.,  71.,  47.,
        32.,  26.,  37.,  45.,  29.,  51.,  30.,  48.,  45.,  37.,  25.,
        43.,  36.,  28.,  42.,  19.,  11.,  59.,  60.,  54.,  49.,  26.,
        24.,  83.,  27.,  28., 100.,  40.,  26.,  56.,  71.,  71.,  28.,
        63.,  58.,  19.,  36.,  17.,  41.,  82.,  46.,  39.,  46.,  50.,
        48.,   9.,  40.,  47.,  21.,  48.,  55.,  54.,  41.,  19.,  15.,
        25.,  49.,  59.,  83.,  46.,  42.,  74.,  69.,   8.,  37.,  32.,
        33.,  19.,  31.,  73.,  36.,  34.,  58.,  35.,  65.,  78.,  60.,
        18.,   6.,  30.,  39.,  23.,  39.,  57.,  37.,  43.,  48.,  23.,
        39.,  19.,  31.,  31.,  37.,  40.,  34.,  59.,  35.,  17.,   7.,
        70.,  58.,  69.,  41.,  58.,  37.,  67.,  2

In [35]:
# feature 12 - spellchecker
import enchant
d = enchant.Dict('en-US')
feature12 = np.array([])
words_new = [[]]
for ix in range(data8.shape[0]):
    a=0
    for w in words_updated[ix]:
        w = str(w)
        if(d.check(w)):
            a+=1;
    feature12 = np.append(feature12,a)
feature12

array([623., 774., 840., 688., 579., 553., 758., 290., 725., 495., 411.,
       748., 788., 529., 698., 125., 681., 521., 722., 273., 611., 785.,
       409., 811., 354., 650., 610., 822., 215., 734., 691., 811., 708.,
       773., 833., 441., 792., 294., 777., 777., 612., 778., 787., 440.,
       339., 445., 456., 530., 294., 633., 437., 569., 640., 720., 559.,
       620., 472., 357., 545., 318., 277., 771., 636., 591., 747., 232.,
       475., 810., 395., 414., 826., 549., 411., 559., 806., 779., 445.,
       795., 729., 245., 815., 331., 785., 725., 750., 520., 507., 610.,
       536., 244., 526., 599., 290., 755., 615., 620., 485., 269., 165.,
       313., 646., 799., 739., 554., 527., 827., 835., 225., 426., 511.,
       499., 354., 495., 826., 497., 487., 741., 469., 820., 745., 750.,
       282.,  60., 560., 435., 696., 586., 676., 611., 679., 721., 465.,
       664., 340., 454., 688., 489., 483., 402., 704., 506., 170., 244.,
       788., 704., 582., 642., 659., 576., 776., 40

In [36]:
feature = []
feature = np.vstack((feature1,feature2,feature3,feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12))
feature = feature.T
feature.shape

(723, 12)

In [37]:
# feature1= feature1.reshape(-1,1)
# print(feature1.shape)
# feature2 = feature2.reshape(-1,1)
# print(feature2.shape)
# feature3= feature3.reshape(-1,1)
# print(feature3.shape)
# feature4 = feature4.reshape(-1,1)
# print(feature4.shape)
# feature5= feature5.reshape(-1,1)
# print(feature5.shape)
# feature6 = feature6.reshape(-1,1)
# print(feature6.shape)
# feature7= feature7.reshape(-1,1)
# print(feature7.shape)
# feature8 = feature8.reshape(-1,1)
# print(feature8.shape)
# feature9 = feature9.reshape(-1,1)
# print(feature9.shape)
# feature10= feature10.reshape(-1,1)
# print(feature10.shape)
# feature11 = feature11.reshape(-1,1)
# print(feature11.shape)
# feature.reshape(1783,2)
# feature.shape

In [38]:
Y= data8['domain1_score']
Y = Y.fillna(0.1)

In [39]:
Y.shape
Y = Y.values

In [40]:
## Model

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
lr = LinearRegression()
lr.fit(feature,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [43]:
y1 = lr.predict(feature)
type(y1)

numpy.ndarray

In [44]:
from sklearn.metrics import accuracy_score, mean_absolute_error

# The following 3 functions have been taken from Ben Hamner's github repository
# https://github.com/benhamner/Metrics
def confusion_matrix(rater_a, rater_b, min_rating=None, max_rating=None):
    """
    Returns the confusion matrix between rater's ratings
    """
    assert(len(rater_a) == len(rater_b))
    if min_rating is None:
        min_rating = min(rater_a + rater_b)
    if max_rating is None:
        max_rating = max(rater_a + rater_b)
    num_ratings = int(max_rating - min_rating + 1)
    conf_mat = [[0 for i in range(num_ratings)]
                for j in range(num_ratings)]
    for a, b in zip(rater_a, rater_b):
        conf_mat[a - min_rating][b - min_rating] += 1
    return conf_mat


def histogram(ratings, min_rating=None, max_rating=None):
    """
    Returns the counts of each type of rating that a rater made
    """
    if min_rating is None:
        min_rating = min(ratings)
    if max_rating is None:
        max_rating = max(ratings)
    num_ratings = int(max_rating - min_rating + 1)
    hist_ratings = [0 for x in range(num_ratings)]
    for r in ratings:
        hist_ratings[r - min_rating] += 1
    return hist_ratings


def quadratic_weighted_kappa(y, y_pred):
    """
    Calculates the quadratic weighted kappa
    axquadratic_weighted_kappa calculates the quadratic weighted kappa
    value, which is a measure of inter-rater agreement between two raters
    that provide discrete numeric ratings.  Potential values range from -1
    (representing complete disagreement) to 1 (representing complete
    agreement).  A kappa value of 0 is expected if all agreement is due to
    chance.
    quadratic_weighted_kappa(rater_a, rater_b), where rater_a and rater_b
    each correspond to a list of integer ratings.  These lists must have the
    same length.
    The ratings should be integers, and it is assumed that they contain
    the complete range of possible ratings.
    quadratic_weighted_kappa(X, min_rating, max_rating), where min_rating
    is the minimum possible rating, and max_rating is the maximum possible
    rating
    """
    rater_a = y
    rater_b = y_pred
    min_rating=None
    max_rating=None
    rater_a = np.array(rater_a, dtype=int)
    rater_b = np.array(rater_b, dtype=int)
    assert(len(rater_a) == len(rater_b))
    if min_rating is None:
        min_rating = min(min(rater_a), min(rater_b))
    if max_rating is None:
        max_rating = max(max(rater_a), max(rater_b))
    conf_mat = confusion_matrix(rater_a, rater_b,
                                min_rating, max_rating)
    num_ratings = len(conf_mat)
    num_scored_items = float(len(rater_a))

    hist_rater_a = histogram(rater_a, min_rating, max_rating)
    hist_rater_b = histogram(rater_b, min_rating, max_rating)

    numerator = 0.0
    denominator = 0.0

    for i in range(num_ratings):
        for j in range(num_ratings):
            expected_count = (hist_rater_a[i] * hist_rater_b[j]
                              / num_scored_items)
            d = pow(i - j, 2.0) / pow(num_ratings - 1, 2.0)
            numerator += d * conf_mat[i][j] / num_scored_items
            denominator += d * expected_count / num_scored_items

    return (1.0 - numerator / denominator)
    
quadratic_weighted_kappa(Y, y1)

0.634510574930226