In [1]:
import numpy as np
import nltk
from sklearn.metrics import cohen_kappa_score as k

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('/home/ramendra/virtualenv_name/data/training_set_rel3.xls')
data

essay_id  essay_set                                              essay  \
0             1          1  Dear local newspaper, I think effects computer...   
1             2          1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2             3          1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3             4          1  Dear Local Newspaper, @CAPS1 I have found that...   
4             5          1  Dear @LOCATION1, I know having computers has a...   
5             6          1  Dear @LOCATION1, I think that computers have a...   
6             7          1  Did you know that more and more people these d...   
7             8          1  @PERCENT1 of people agree that computers make ...   
8             9          1  Dear reader, @ORGANIZATION1 has had a dramatic...   
9            10          1  In the @LOCATION1 we have the technology of a ...   
10           11          1  Dear @LOCATION1, @CAPS1 people acknowledge the...   
11           12          1  Dear @CAPS1 @CAPS2 I feel that computers do ta...   
12           13          1  Dear local newspaper I raed ur argument on the...   
13           14          1  My three detaileds for this news paper article...   
14           15          1  Dear, In this world today we should have every...   
15           16          1  Dear @ORGANIZATION1, The computer blinked to l...   
16           17          1  Dear Local Newspaper, I belive that computers ...   
17           18          1  Dear Local Newspaper, I must admit that the ex...   
18           19          1  I aegre waf the evansmant ov tnachnolage. The ...   
19           20          1  Well computers can be a good or a bad thing. I...   
20           21          1  Dear @CAPS1 of the @CAPS2 @CAPS3 daily, I am w...   
21           22          1  Dear local Newspaper @CAPS1 a take all your co...   
22           23          1  Dear local newspaper, @CAPS1 you ever see a ch...   
23           24          1  Dear local newspaper, I've heard that not many...   
24           25          1  Dear @CAPS1, @CAPS2 off, I beileve that comput...   
25           26          1  Do you think that computers are useless? Or do...   
26           27          1  Computers a good because you can get infermati...   
27           28          1  Dear Newspaper, Computers are high tec and hav...   
28           29          1  Dear local newspaper, @CAPS1 people throughout...   
29           30          1  Dear Newspaper People, I think that computers ...   
...         ...        ...                                                ...   
12948     21592          8   We all understand the benefits of laughter. L...   
12949     21594          8        It was midsummer, and i could feel the c...   
12950     21595          8   Have you ever experienced a time with your fr...   
12951     21596          8   I woke up just like any other day happy yet l...   
12952     21598          8   Laughter is an important part of my life, eit...   
12953     21599          8   I sat at the table, speechless, as they told ...   
12954     21601          8   As I remember back, it was @DATE1. It was a h...   
12955     21603          8   Those eyes, it was like I was looking out int...   
12956     21604          8  Some say that laugh is the common language bet...   
12957     21605          8   Laughter is an integral element to many situa...   
12958     21606          8  One time I was at my friend @PERSON1's house, ...   
12959     21607          8   LAUGHTER @CAPS1 knows that laughter is a heal...   
12960     21608          8  One thing that people in the world love to do ...   
12961     21609          8   Laughter, to me, is an important aspect of my...   
12962     21610          8   People always say that the worst parts of lif...   
12963     21611          8   Why is it that people can look back at someth...   
12964     21613          8   Before my best friend moved away, we would st...   
12965     21615          8            

In [4]:
a=[ix for ix in range(10,28)]
a = np.array(a)
a = np.append(a,np.array([0,3,4,5,7,8]))
# # a.append([0,3,4,5,7,8])
data.drop(data.columns[a],axis=1,inplace=True)
data

essay_set                                              essay  \
0              1  Dear local newspaper, I think effects computer...   
1              1  Dear @CAPS1 @CAPS2, I believe that using compu...   
2              1  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...   
3              1  Dear Local Newspaper, @CAPS1 I have found that...   
4              1  Dear @LOCATION1, I know having computers has a...   
5              1  Dear @LOCATION1, I think that computers have a...   
6              1  Did you know that more and more people these d...   
7              1  @PERCENT1 of people agree that computers make ...   
8              1  Dear reader, @ORGANIZATION1 has had a dramatic...   
9              1  In the @LOCATION1 we have the technology of a ...   
10             1  Dear @LOCATION1, @CAPS1 people acknowledge the...   
11             1  Dear @CAPS1 @CAPS2 I feel that computers do ta...   
12             1  Dear local newspaper I raed ur argument on the...   
13             1  My three detaileds for this news paper article...   
14             1  Dear, In this world today we should have every...   
15             1  Dear @ORGANIZATION1, The computer blinked to l...   
16             1  Dear Local Newspaper, I belive that computers ...   
17             1  Dear Local Newspaper, I must admit that the ex...   
18             1  I aegre waf the evansmant ov tnachnolage. The ...   
19             1  Well computers can be a good or a bad thing. I...   
20             1  Dear @CAPS1 of the @CAPS2 @CAPS3 daily, I am w...   
21             1  Dear local Newspaper @CAPS1 a take all your co...   
22             1  Dear local newspaper, @CAPS1 you ever see a ch...   
23             1  Dear local newspaper, I've heard that not many...   
24             1  Dear @CAPS1, @CAPS2 off, I beileve that comput...   
25             1  Do you think that computers are useless? Or do...   
26             1  Computers a good because you can get infermati...   
27             1  Dear Newspaper, Computers are high tec and hav...   
28             1  Dear local newspaper, @CAPS1 people throughout...   
29             1  Dear Newspaper People, I think that computers ...   
...          ...                                                ...   
12948          8   We all understand the benefits of laughter. L...   
12949          8        It was midsummer, and i could feel the c...   
12950          8   Have you ever experienced a time with your fr...   
12951          8   I woke up just like any other day happy yet l...   
12952          8   Laughter is an important part of my life, eit...   
12953          8   I sat at the table, speechless, as they told ...   
12954          8   As I remember back, it was @DATE1. It was a h...   
12955          8   Those eyes, it was like I was looking out int...   
12956          8  Some say that laugh is the common language bet...   
12957          8   Laughter is an integral element to many situa...   
12958          8  One time I was at my friend @PERSON1's house, ...   
12959          8   LAUGHTER @CAPS1 knows that laughter is a heal...   
12960          8  One thing that people in the world love to do ...   
12961          8   Laughter, to me, is an important aspect of my...   
12962          8   People always say that the worst parts of lif...   
12963          8   Why is it that people can look back at someth...   
12964          8   Before my best friend moved away, we would st...   
12965          8                                @ORGANIZATION1  ...   
12966          8   Morose and somnolent, I woke up. I woke up to...   
12967          8   A while back my mom had decided to send me to...   
12968          8                              I dont like computers   
12969          8   Everyone knows how important a laugh can be. ...   
12970          8   Laughter is an important part of my family. W...   
12971          8   laughter is an important part of any kind of ...   
12972          8  Sometime ago 

In [5]:
data1 = data.loc[data['essay_set']==1]
data2 = data.loc[data['essay_set']==2]
data3 = data.loc[data['essay_set']==3]
data4 = data.loc[data['essay_set']==4]
data5 = data.loc[data['essay_set']==5]
data6 = data.loc[data['essay_set']==6]
data7 = data.loc[data['essay_set']==7]
data8 = data.loc[data['essay_set']==8]

In [6]:
data1.drop(data1.columns[[3]],axis=1,inplace=True)
data3.drop(data3.columns[[3]],axis=1,inplace=True)
data4.drop(data4.columns[[3]],axis=1,inplace=True)
data5.drop(data5.columns[[3]],axis=1,inplace=True)
data6.drop(data6.columns[[3]],axis=1,inplace=True)
data7.drop(data7.columns[[3]],axis=1,inplace=True)
data8.drop(data8.columns[[3]],axis=1,inplace=True)
data4

/home/ramendra/.local/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


essay_set                                              essay  \
5309          4  The author concludes the story with this becau...   
5310          4  The narrater has that in with Paragraph becuse...   
5311          4  The author concludes the story with that passa...   
5312          4  The author ended the story with this paragraph...   
5313          4  The author concludes the story with this parag...   
5314          4  The reason the author concludes the story with...   
5315          4  The story ended with the author saying, "when ...   
5316          4  I believe that the author concludes the story ...   
5317          4  The author would conclude the story with that ...   
5318          4  In the story, "Winter Hibiscus," by Minfong Ho...   
5319          4  The author concludes the story with this parag...   
5320          4  I think he concluded the story with paragraph ...   
5321          4  The author concludes the story with this parag...   
5322          4  The author concludes the story with this parag...   
5323          4  Why the author concludes the story with this p...   
5324          4  He states this as the conclusion because it sh...   
5325          4  I believe the author concludes the story with ...   
5326          4  The arthur uses it because Saeng got confidenc...   
5327          4  the author concludes the story this way becaus...   
5328          4  I think the author ends the story with this pa...   
5329          4  I think that the author concludes the story wi...   
5330          4  They probably ended it like that to build susp...   
5331          4   In” Winter Hibiscus,” by Minfong Ho, the main...   
5332          4  The author concludes the story with this parag...   
5333          4  The author concludes this story with this para...   
5334          4  In the story, “Winter Hibiscus”, the author en...   
5335          4  I think that she ended the story like that bec...   
5336          4  The author concludes the story with this parag...   
5337          4  By ending the story with the idea of retaking ...   
5338          4  The author concluded the story with that speci...   
...         ...                                                ...   
7051          4  Coming back from failing her driving test, Sae...   
7052          4  The story of “Winter Hibiscus” is a prolonged ...   
7053          4  In “Winter Hibiscus” by Minfong Ho, Saeng has ...   
7054          4  Since it is getting close to winter the geese ...   
7055          4  The auther concludes the story with this parag...   
7056          4  The author concludes her story with that last ...   
7057          4  The author is relating to that when the geese ...   
7058          4  I think the Author ends this as the concluding...   
7059          4  the author concludes the story with that parag...   
7060          4  I think the author concludes the story with th...   
7061          4  In the short story “Winter Hibiscus” Saeng dec...   
7062          4  The author concludes the story with that parag...   
7063          4  I think that the author concludes the story li...   
7064          4  The last paragraph of the story was: “When the...   
7065          4  Saeng told her mother that she failed the test...   
7066          4  The Author concludes that, when the geese come...   
7067          4  The reason the author chose this paragraph is ...   
7068          4  The author concludes the story with the paragr...   
7069          4  The author concludes the story with this sente...   
7070          4  The author concludes the story with that parag...   
7071          4  The author concludes the story with this parag...   
7072          4  She ends it with that statement to show that s...   
7073          4  She realized that things come and go but also ...   
7074          4  The author ended the story with that paragraph...   
7075          4  I think the author concludes this story like t...   
7076          4 

## TRAINING


In [7]:
data4

essay_set                                              essay  \
5309          4  The author concludes the story with this becau...   
5310          4  The narrater has that in with Paragraph becuse...   
5311          4  The author concludes the story with that passa...   
5312          4  The author ended the story with this paragraph...   
5313          4  The author concludes the story with this parag...   
5314          4  The reason the author concludes the story with...   
5315          4  The story ended with the author saying, "when ...   
5316          4  I believe that the author concludes the story ...   
5317          4  The author would conclude the story with that ...   
5318          4  In the story, "Winter Hibiscus," by Minfong Ho...   
5319          4  The author concludes the story with this parag...   
5320          4  I think he concluded the story with paragraph ...   
5321          4  The author concludes the story with this parag...   
5322          4  The author concludes the story with this parag...   
5323          4  Why the author concludes the story with this p...   
5324          4  He states this as the conclusion because it sh...   
5325          4  I believe the author concludes the story with ...   
5326          4  The arthur uses it because Saeng got confidenc...   
5327          4  the author concludes the story this way becaus...   
5328          4  I think the author ends the story with this pa...   
5329          4  I think that the author concludes the story wi...   
5330          4  They probably ended it like that to build susp...   
5331          4   In” Winter Hibiscus,” by Minfong Ho, the main...   
5332          4  The author concludes the story with this parag...   
5333          4  The author concludes this story with this para...   
5334          4  In the story, “Winter Hibiscus”, the author en...   
5335          4  I think that she ended the story like that bec...   
5336          4  The author concludes the story with this parag...   
5337          4  By ending the story with the idea of retaking ...   
5338          4  The author concluded the story with that speci...   
...         ...                                                ...   
7051          4  Coming back from failing her driving test, Sae...   
7052          4  The story of “Winter Hibiscus” is a prolonged ...   
7053          4  In “Winter Hibiscus” by Minfong Ho, Saeng has ...   
7054          4  Since it is getting close to winter the geese ...   
7055          4  The auther concludes the story with this parag...   
7056          4  The author concludes her story with that last ...   
7057          4  The author is relating to that when the geese ...   
7058          4  I think the Author ends this as the concluding...   
7059          4  the author concludes the story with that parag...   
7060          4  I think the author concludes the story with th...   
7061          4  In the short story “Winter Hibiscus” Saeng dec...   
7062          4  The author concludes the story with that parag...   
7063          4  I think that the author concludes the story li...   
7064          4  The last paragraph of the story was: “When the...   
7065          4  Saeng told her mother that she failed the test...   
7066          4  The Author concludes that, when the geese come...   
7067          4  The reason the author chose this paragraph is ...   
7068          4  The author concludes the story with the paragr...   
7069          4  The author concludes the story with this sente...   
7070          4  The author concludes the story with that parag...   
7071          4  The author concludes the story with this parag...   
7072          4  She ends it with that statement to show that s...   
7073          4  She realized that things come and go but also ...   
7074          4  The author ended the story with that paragraph...   
7075          4  I think the author concludes this story like t...   
7076          4 

In [8]:
from nltk.tokenize import word_tokenize

In [9]:
data4.shape[0]
data4 = data4.reset_index()

In [10]:
data4['essay'][0]

'The author concludes the story with this because gardens cannot grow with snow on the ground. So she she figurers when all the snow is melted she”ll try to grow another one. I feel as if she wasn’t  happy enough to grow another garden I think she should be more interested in growin it then disappointed.    '

In [11]:
allsentences = np.array([data4['essay'][ix] for ix in range(data4.shape[0])])
print(allsentences.shape)
allsentences_list = allsentences.tolist()

(1772,)


In [12]:
from nltk.tokenize import sent_tokenize, word_tokenize
# words1 = word_tokenize(allsentences[0])
# type(words1)

In [13]:
# words = word_tokenize(allsentences[0])
# print(words)
from nltk.tokenize import RegexpTokenizer
import re
tokenizer1 = re.compile(r'\b[A-Z][A-Z0-9]+\b')
tokenizer2 = RegexpTokenizer('[ \d \' \. \, \: \; \? \- \! \( \) \s\@]')
prop_nouns=[[] for ix in range(data4.shape[0])]
for ix in range(data4.shape[0]):
        prop_nouns[ix] = np.unique(np.append(prop_nouns[ix],np.array(tokenizer2.tokenize(allsentences[ix]))))
        prop_nouns[ix] = np.unique(np.append(prop_nouns[ix],np.array(tokenizer1.findall(allsentences[ix]))))
        prop_nouns[ix] = prop_nouns[ix].tolist()

In [14]:
words = [[] for ix in range(data4.shape[0])]
for ix in range(data4.shape[0]):
    words[ix] = np.array(word_tokenize(allsentences[ix]))

# feature1-word count
feature1 = np.array([])
words_updated = [[] for ix in range(data4.shape[0])]
for ix in range(data4.shape[0]):
    words_updated[ix] = np.array([w for w in words[ix] if w not  in prop_nouns[ix]])
    a = list(words_updated[ix].shape)
    feature1 = np.append(feature1,a[0])

words_updated = np.array(words_updated)
feature1

array([ 61.,  39., 135., ...,  62.,  39.,  75.])

In [15]:
# feature2-sentence count
sentence = [[] for ix in range(data4.shape[0])]
feature2 = np.array([])
for ix in range(data4.shape[0]):
    sentence[ix] = np.array(sent_tokenize(allsentences[ix]))
    feature2 = np.append(feature2,sentence[ix].shape[0])

feature2

array([3., 2., 5., ..., 3., 2., 5.])

In [16]:
# feature3 - average word length
feature3 = np.array([])
for ix in range(data4.shape[0]):
    feature3 = np.append(feature3, np.sum((len(w)/words_updated[ix].shape[0]) for w in words_updated[ix]))

feature3

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([4.01639344, 4.30769231, 4.72592593, ..., 4.17741935, 4.38461538,
       4.2       ])

In [17]:
stopwords = np.array([])
for ix in range(data4.shape[0]):
    stopwords = np.append(stopwords, np.array(w for w in prop_nouns[ix]))

stopwords.tolist()
stopwords = set(stopwords)
allsentences.shape

(1772,)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words=stopwords,ngram_range=(1,2))
cv.fit_transform(allsentences[:500]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
a1 = cv.transform(allsentences_list).toarray()

In [20]:
#feature 4: weighted word-counts
feature4 = np.array([])
for ix in range(data4.shape[0]):
    feature4 = np.append(feature4, np.sum(a for a in a1[ix]))
    
feature4

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([109.,  79., 271., ...,  96.,  64., 116.])

In [21]:
feature4.shape

(1772,)

In [22]:
#feature5: Punctuation
feature5 = np.array([])
for ix in range(data4.shape[0]):
    a = np.array(tokenizer2.tokenize(allsentences[ix]))
    feature5 = np.append(feature5, len(a))
    
feature5

array([ 63.,  43., 150., ...,  62.,  38.,  79.])

In [23]:
feature5.shape

(1772,)

In [24]:
# feature 6: Comma Separation
feature6 = np.array([])
for ix in range(data4.shape[0]):
    feature6 = np.append(feature6,np.sum(words[ix]==','))
                         
feature6

array([0., 0., 6., ..., 2., 0., 0.])

In [25]:
feature6.shape

(1772,)

In [26]:
# feature 7: Proper Noun
feature7 = np.array([])
for ix in range(data4.shape[0]):
    feature7 = np.append(feature7,np.sum(words[ix]=='@'))
                         
feature7

array([0., 0., 1., ..., 0., 0., 0.])

In [27]:
feature7.shape

(1772,)

In [28]:
##GRAMMATICAL EXTRACTION
words_updated = words_updated.tolist()

In [29]:
# nltk.download('averaged_perceptron_tagger')
tagged = [[] for ix in range(data4.shape[0])]
for ix in range(data4.shape[0]):
    tagged[ix] = nltk.pos_tag(word_tokenize(allsentences[ix]))
np.array(tagged[0]).shape

(64, 2)

In [30]:
# feature8 - noun
feature8 = np.array([])
for ix in range(data4.shape[0]):
    feature8 = np.append(feature8,np.sum(x[1]=='NN' or x[1]=='NNS' or x[1] == 'NNP' for x in tagged[ix]))

feature8

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([12.,  8., 44., ..., 18.,  9., 17.])

In [31]:
feature8.shape

(1772,)

In [32]:
# feature9 - verb
feature9 = np.array([])
for ix in range(data4.shape[0]):
    feature9 = np.append(feature9,np.sum(x[1]=='VB' or x[1]=='VBD' or x[1] == 'VBG' for x in tagged[ix]))

feature9

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([ 7.,  1.,  9., ...,  7.,  5., 14.])

In [33]:
# feature10 - adjective
feature10 = np.array([])
for ix in range(data4.shape[0]):
    feature10 = np.append(feature10,np.sum(x[1]=='JJ' or x[1]=='JJR' or x[1] == 'JJS' for x in tagged[ix]))

feature10

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([3., 1., 8., ..., 3., 2., 5.])

In [34]:
# feature 11 - adverb
feature11 = np.array([])
for ix in range(data4.shape[0]):
    feature11 = np.append(feature11,np.sum(x[1]=='RB' or x[1]=='RBR' or x[1] == 'RBS' for x in tagged[ix]))

feature11

/home/ramendra/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  after removing the cwd from sys.path.


array([4., 2., 4., ..., 2., 3., 3.])

In [35]:
# feature 12 - spellchecker
import enchant
d = enchant.Dict('en-US')
feature12 = np.array([])
words_new = [[]]
for ix in range(data4.shape[0]):
    a=0
    for w in words_updated[ix]:
        w = str(w)
        if(d.check(w)):
            a+=1;
    feature12 = np.append(feature12,a)
feature12

array([ 56.,  30., 131., ...,  56.,  35.,  73.])

In [36]:
feature = []
feature = np.vstack((feature1,feature2,feature3,feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12))
feature = feature.T
feature.shape

(1772, 12)

In [37]:
# feature1= feature1.reshape(-1,1)
# print(feature1.shape)
# feature2 = feature2.reshape(-1,1)
# print(feature2.shape)
# feature3= feature3.reshape(-1,1)
# print(feature3.shape)
# feature4 = feature4.reshape(-1,1)
# print(feature4.shape)
# feature5= feature5.reshape(-1,1)
# print(feature5.shape)
# feature6 = feature6.reshape(-1,1)
# print(feature6.shape)
# feature7= feature7.reshape(-1,1)
# print(feature7.shape)
# feature8 = feature8.reshape(-1,1)
# print(feature8.shape)
# feature9 = feature9.reshape(-1,1)
# print(feature9.shape)
# feature10= feature10.reshape(-1,1)
# print(feature10.shape)
# feature11 = feature11.reshape(-1,1)
# print(feature11.shape)
# feature.reshape(1783,2)
# feature.shape

In [38]:
Y= data4['domain1_score']
Y = Y.fillna(0.1)

In [39]:
Y.shape
Y = Y.values

In [40]:
## Model

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
lr = LinearRegression()
lr.fit(feature,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [43]:
y1 = lr.predict(feature)
type(y1)

numpy.ndarray

In [44]:
from sklearn.metrics import accuracy_score, mean_absolute_error

# The following 3 functions have been taken from Ben Hamner's github repository
# https://github.com/benhamner/Metrics
def confusion_matrix(rater_a, rater_b, min_rating=None, max_rating=None):
    """
    Returns the confusion matrix between rater's ratings
    """
    assert(len(rater_a) == len(rater_b))
    if min_rating is None:
        min_rating = min(rater_a + rater_b)
    if max_rating is None:
        max_rating = max(rater_a + rater_b)
    num_ratings = int(max_rating - min_rating + 1)
    conf_mat = [[0 for i in range(num_ratings)]
                for j in range(num_ratings)]
    for a, b in zip(rater_a, rater_b):
        conf_mat[a - min_rating][b - min_rating] += 1
    return conf_mat


def histogram(ratings, min_rating=None, max_rating=None):
    """
    Returns the counts of each type of rating that a rater made
    """
    if min_rating is None:
        min_rating = min(ratings)
    if max_rating is None:
        max_rating = max(ratings)
    num_ratings = int(max_rating - min_rating + 1)
    hist_ratings = [0 for x in range(num_ratings)]
    for r in ratings:
        hist_ratings[r - min_rating] += 1
    return hist_ratings


def quadratic_weighted_kappa(y, y_pred):
    """
    Calculates the quadratic weighted kappa
    axquadratic_weighted_kappa calculates the quadratic weighted kappa
    value, which is a measure of inter-rater agreement between two raters
    that provide discrete numeric ratings.  Potential values range from -1
    (representing complete disagreement) to 1 (representing complete
    agreement).  A kappa value of 0 is expected if all agreement is due to
    chance.
    quadratic_weighted_kappa(rater_a, rater_b), where rater_a and rater_b
    each correspond to a list of integer ratings.  These lists must have the
    same length.
    The ratings should be integers, and it is assumed that they contain
    the complete range of possible ratings.
    quadratic_weighted_kappa(X, min_rating, max_rating), where min_rating
    is the minimum possible rating, and max_rating is the maximum possible
    rating
    """
    rater_a = y
    rater_b = y_pred
    min_rating=None
    max_rating=None
    rater_a = np.array(rater_a, dtype=int)
    rater_b = np.array(rater_b, dtype=int)
    assert(len(rater_a) == len(rater_b))
    if min_rating is None:
        min_rating = min(min(rater_a), min(rater_b))
    if max_rating is None:
        max_rating = max(max(rater_a), max(rater_b))
    conf_mat = confusion_matrix(rater_a, rater_b,
                                min_rating, max_rating)
    num_ratings = len(conf_mat)
    num_scored_items = float(len(rater_a))

    hist_rater_a = histogram(rater_a, min_rating, max_rating)
    hist_rater_b = histogram(rater_b, min_rating, max_rating)

    numerator = 0.0
    denominator = 0.0

    for i in range(num_ratings):
        for j in range(num_ratings):
            expected_count = (hist_rater_a[i] * hist_rater_b[j]
                              / num_scored_items)
            d = pow(i - j, 2.0) / pow(num_ratings - 1, 2.0)
            numerator += d * conf_mat[i][j] / num_scored_items
            denominator += d * expected_count / num_scored_items

    return (1.0 - numerator / denominator)
    
quadratic_weighted_kappa(Y, y1)

0.5865637221216844